server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web: DEBUG



# Optional configurations for detailed request logging
request:
  logging:
    filter:
      include-client-info: true
      include-query-string: true
      include-payload: true
      max-payload-length: 10000


